version: "3"

services:
  vote:
    build: ./vote
    depends_on:
      - "redis"
    volumes:
      - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier1
    
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - front-tier1
      - back-tier
  
  worker:
    build: ./worker
    depends_on:
      - "redis"
      - "db"
    networks:
      - back-tier
  
  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
      - front-tier2
    
  result:
    build: ./result
    depends_on:
      - db
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
    networks:
      - front-tier2
 
volumes:
   db-data:

networks:
  front-tier1:
  back-tier:
  front-tier2:

